# Generated by Django 5.0.2 on 2024-02-27 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0003_biggoal_antigoal_checkpointgoal_dailysystems'),
    ]

    operations = [
        migrations.AddField(
            model_name='biggoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailySystemCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals_tracker.dailysystems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'daily_system', 'date')},
            },
        ),
    ]
