# Generated by Django 5.0.2 on 2024-03-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0005_alter_biggoal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biggoal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkpointgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
