# Generated by Django 5.0.2 on 2024-03-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0006_alter_biggoal_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySystems',
            new_name='DailySystem',
        ),
    ]
