# Generated by Django 5.0.2 on 2024-03-17 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0007_rename_dailysystems_dailysystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointgoal',
            name='deadline',
        ),
        migrations.AddField(
            model_name='biggoal',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checkpointgoal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
