# Generated by Django 5.0.2 on 2024-04-30 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0008_remove_checkpointgoal_deadline_biggoal_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysystemcheckin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailysystemcheckin',
            name='big_goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goals_tracker.biggoal'),
        ),
    ]
