# Generated by Django 5.0.2 on 2024-05-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0009_alter_dailysystemcheckin_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySystemCheckIn',
        ),
    ]
