# Generated by Django 5.0.2 on 2024-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0011_dailysystemcheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysystemcheckin',
            name='date',
            field=models.DateField(),
        ),
    ]
