# Generated by Django 5.0.2 on 2024-06-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0012_alter_dailysystemcheckin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointgoal',
            name='big_goal',
        ),
        migrations.DeleteModel(
            name='AntiGoal',
        ),
        migrations.DeleteModel(
            name='CheckpointGoal',
        ),
    ]
