# Generated by Django 5.0.2 on 2024-08-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0013_remove_checkpointgoal_big_goal_delete_antigoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
