# Generated by Django 5.0.2 on 2024-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0015_remove_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='biggoal',
            name='categories',
            field=models.ManyToManyField(related_name='goals', to='goals_tracker.category'),
        ),
    ]
