# Generated by Django 5.0.2 on 2024-08-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals_tracker', '0016_category_biggoal_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biggoal',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
