# Generated by Django 5.0.1 on 2024-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topgoal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
