# Generated by Django 5.0.1 on 2024-01-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dailygoal_completed_topgoal_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygoal',
            old_name='completed',
            new_name='mark_as_complete',
        ),
        migrations.RenameField(
            model_name='topgoal',
            old_name='completed',
            new_name='mark_as_complete',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', related_query_name='daily_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='top_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', related_query_name='daily_goal', to='base.topgoal'),
        ),
        migrations.AlterField(
            model_name='topgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
